drop database IF exists Rick_and_Morty_Shopping_DB;

CREATE DATABASE Rick_and_Morty_Shopping_DB;

USE Rick_and_Morty_Shopping_DB;
CREATE TABLE CLIENTE(
	CLI_PK_ID_CLIENTE INT AUTO_INCREMENT PRIMARY KEY,
    CLI_NOME VARCHAR(80),
    CLI_ENDERECO VARCHAR(80),
    CLI_BAIRRO VARCHAR(80),
    CLI_CIDADE VARCHAR(80),
    CLI_UF VARCHAR(3),
    CLI_CEP VARCHAR(80),
    CLI_TELEFONE VARCHAR(80)
);

CREATE TABLE USUARIO(
	USU_ID_USUARIO INT auto_increment PRIMARY KEY,
    USU_NOME VARCHAR(100),
    USU_LOGIN VARCHAR(90),
    USU_SENHA VARCHAR(15)
);

CREATE TABLE FORNECEDOR(
FOR_PK_COD_FORNECEDOR INT AUTO_INCREMENT PRIMARY KEY,
FOR_CNPJ VARCHAR(20),
FOR_NOME VARCHAR(90),
FOR_ENDERECO VARCHAR(90),
FOR_BAIRRO VARCHAR(90),
FOR_CIDADE VARCHAR(90),
FOR_UF VARCHAR(3),
FOR_CEP VARCHAR(20),
FOR_TELEFONE VARCHAR(90)
);

CREATE TABLE PRODUTOS(
	PRO_PK_PRODUTOS INT auto_increment primary KEY,
    PRO_NOME VARCHAR(90),
    PRO_VALOR DOUBLE,
    PRO_ESTOQUE INT/*NO DIAGRAMA ESTÁ COMO ESTOQUE*/,
    DESCRICAO VARCHAR(300),
    FK_PRO_COD_FORN INT,
    FOREIGN KEY (FK_PRO_COD_FORN) REFERENCES FORNECEDOR(FOR_PK_COD_FORNECEDOR)
    );
    
CREATE TABLE VENDAS(

);
    
CREATE TABLE VENDAS_PRODUTOS(
	PK_VENDAS_PRODUTOS INT auto_increment PRIMARY KEY,
    FK_VEN_VALOR_PRODUTO DOUBLE,
    FK_COD_PRODUTO INT,
    
    
);


